package com.po4yka.runatal.data.local.migration

import androidx.sqlite.SQLiteConnection
import com.po4yka.runatal.data.seed.QuoteSeedData
import com.po4yka.runatal.domain.transliteration.YoungerFutharkTransliterator
import com.po4yka.runatal.domain.transliteration.ElderFutharkTransliterator
import com.po4yka.runatal.domain.transliteration.CirthTransliterator
import com.po4yka.runatal.domain.transliteration.RunicTransliterator

/** Repairs proven derived strings while retaining historical output in its structured cache records. */
internal object YoungerFutharkRenderingMigration {

    fun migrate(connection: SQLiteConnection) {
        repairHistoricalSnapshots(connection)
        val canonicalSeeds = QuoteSeedData.getLegacyQuotes()
        val transliterator = YoungerFutharkTransliterator()
        readRenderings(connection).filter { row ->
            row.glyphs == legacyRendering(row.textLatin) || canonicalSeeds.any { seed ->
                seed.textLatin == row.textLatin && seed.author == row.author && seed.runicYounger == row.glyphs
            }
        }.forEach { row ->
            connection.prepare(
                "UPDATE quotes SET runicYounger = ? WHERE id = ? AND runicYounger = ?"
            ).use { statement ->
                statement.bindText(1, transliterator.transliterate(row.textLatin))
                statement.bindLong(2, row.id)
                statement.bindText(3, row.glyphs)
                statement.step()
            }
        }
        repairReference(connection, "Sol", "ᛊ", "ᛋ")
        repairReference(connection, "Madr", "ᛗ", "ᛘ")
    }

    private fun readRenderings(connection: SQLiteConnection): List<StoredRendering> {
        return connection.prepare(
            "SELECT id, textLatin, author, runicYounger FROM quotes WHERE runicYounger IS NOT NULL"
        ).use { statement ->
            buildList {
                while (statement.step()) {
                    add(
                        StoredRendering(
                            id = statement.getLong(0),
                            textLatin = statement.getText(1),
                            author = statement.getText(2),
                            glyphs = statement.getText(3)
                        )
                    )
                }
            }
        }
    }

    private fun repairHistoricalSnapshots(connection: SQLiteConnection) {
        val profiles = listOf(
            RenderingProfile("ELDER_FUTHARK", "runicElder", ElderFutharkTransliterator()),
            RenderingProfile("YOUNGER_FUTHARK", "runicYounger", YoungerFutharkTransliterator()),
            RenderingProfile("CIRTH", "runicCirth", CirthTransliterator())
        )
        profiles.forEach { profile ->
            val snapshots = connection.prepare(
                "SELECT DISTINCT q.id, q.textLatin, q.${profile.column} FROM quotes q " +
                    "JOIN translation_records t ON t.quoteId = q.id " +
                    "WHERE t.script = ? AND t.sourceText = q.textLatin AND t.glyphOutput = q.${profile.column}"
            ).use { statement ->
                statement.bindText(1, profile.script)
                buildList {
                    while (statement.step()) {
                        add(StoredSnapshot(statement.getLong(0), statement.getText(1), statement.getText(2)))
                    }
                }
            }
            snapshots.forEach { snapshot ->
                connection.prepare(
                    "UPDATE quotes SET ${profile.column} = ? WHERE id = ? AND ${profile.column} = ?"
                ).use { statement ->
                    statement.bindText(1, profile.transliterator.transliterate(snapshot.sourceText))
                    statement.bindLong(2, snapshot.id)
                    statement.bindText(3, snapshot.glyphs)
                    statement.step()
                }
            }
        }
    }

    private data class RenderingProfile(
        val script: String,
        val column: String,
        val transliterator: RunicTransliterator
    )

    private data class StoredSnapshot(val id: Long, val sourceText: String, val glyphs: String)

    private fun repairReference(connection: SQLiteConnection, name: String, oldGlyph: String, newGlyph: String) {
        connection.prepare(
            "UPDATE rune_references SET character = ? " +
                "WHERE script = 'younger_futhark' AND name = ? AND character = ?"
        ).use { statement ->
            statement.bindText(1, newGlyph)
            statement.bindText(2, name)
            statement.bindText(3, oldGlyph)
            statement.step()
        }
    }

    // This obsolete map exists solely to prove that a stored string was generated by the old converter.
    private fun legacyRendering(text: String): String {
        val legacyMap = mapOf(
            'f' to 'ᚠ', 'u' to 'ᚢ', 'v' to 'ᚢ', 'þ' to 'ᚦ', 'a' to 'ᚨ', 'r' to 'ᚱ',
            'k' to 'ᚲ', 'c' to 'ᚲ', 'g' to 'ᚲ', 'h' to 'ᚻ', 'n' to 'ᚾ', 'i' to 'ᛁ',
            'j' to 'ᛁ', 'y' to 'ᛁ', 'p' to 'ᛈ', 'z' to 'ᛊ', 's' to 'ᛊ', 't' to 'ᛏ',
            'b' to 'ᛒ', 'e' to 'ᛖ', 'm' to 'ᛗ', 'l' to 'ᛚ', 'o' to 'ᛟ', 'd' to 'ᚦ',
            'w' to 'ᚢ', 'x' to 'ᚲ', 'q' to 'ᚲ'
        )
        return text.lowercase().replace("th", "ᚦ").replace("ng", "ᚾ")
            .map { legacyMap[it] ?: it }.joinToString("")
    }

    private data class StoredRendering(
        val id: Long,
        val textLatin: String,
        val author: String,
        val glyphs: String
    )
}
